import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from 'next/font/local'
import "@/app/globals.css";
import ConfigProvider from "@/components/features/provider/ConfigProvider";

import { ToastContainer } from 'react-toastify';
import { LazyMotion, domAnimation } from "framer-motion";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const barlowFont = localFont({
  src: [
    { path: "../assets/fonts/Barlow/Barlow-Thin.ttf", weight: "100", style: "normal" },
    { path: "../assets/fonts/Barlow/Barlow-ThinItalic.ttf", weight: "100", style: "italic" },
    { path: "../assets/fonts/Barlow/Barlow-ExtraLight.ttf", weight: "200", style: "normal" },
    { path: "../assets/fonts/Barlow/Barlow-ExtraLightItalic.ttf", weight: "200", style: "italic" },
    { path: "../assets/fonts/Barlow/Barlow-Light.ttf", weight: "300", style: "normal" },
    { path: "../assets/fonts/Barlow/Barlow-LightItalic.ttf", weight: "300", style: "italic" },
    { path: "../assets/fonts/Barlow/Barlow-Regular.ttf", weight: "400", style: "normal" },
    { path: "../assets/fonts/Barlow/Barlow-Italic.ttf", weight: "400", style: "italic" },
    { path: "../assets/fonts/Barlow/Barlow-Medium.ttf", weight: "500", style: "normal" },
    { path: "../assets/fonts/Barlow/Barlow-MediumItalic.ttf", weight: "500", style: "italic" },
    { path: "../assets/fonts/Barlow/Barlow-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../assets/fonts/Barlow/Barlow-SemiBoldItalic.ttf", weight: "600", style: "italic" },
    { path: "../assets/fonts/Barlow/Barlow-Bold.ttf", weight: "700", style: "normal" },
    { path: "../assets/fonts/Barlow/Barlow-BoldItalic.ttf", weight: "700", style: "italic" },
    { path: "../assets/fonts/Barlow/Barlow-ExtraBold.ttf", weight: "800", style: "normal" },
    { path: "../assets/fonts/Barlow/Barlow-ExtraBoldItalic.ttf", weight: "800", style: "italic" },
    { path: "../assets/fonts/Barlow/Barlow-Black.ttf", weight: "900", style: "normal" },
    { path: "../assets/fonts/Barlow/Barlow-BlackItalic.ttf", weight: "900", style: "italic" },
  ],
  variable: "--font-barlow",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      style={{
        overflowX: "hidden"
      }}
      suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="/minify/site.min.css" />
      </head>
      <body
        suppressHydrationWarning
        className={`${barlowFont.className} ${geistSans.variable} antialiased bg-effect stickyCart`}
      >
        <ToastContainer className={"p-0"} />
        <ConfigProvider>
          <LazyMotion features={domAnimation}>
            {children}
          </LazyMotion>
        </ConfigProvider>
        <div className="theme-option">
          <div className="back-to-top">
            <a id="back-to-top" href="#" aria-label="back_to_top">
              <i className="fas fa-chevron-up"></i>
            </a>
          </div>
        </div>
        <div className="bg-overlay"></div>
      </body>
    </html>
  )
}
